name: Deploy to Vercel

# Este "gatilho" diz para a pipeline rodar sempre
# que houver um 'push' na branch 'main'
on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest # A pipeline vai rodar em um servidor Linux
    steps:
      # 1. Baixa o seu código do GitHub para o servidor
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Instala a ferramenta de linha de comando da Vercel
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      # 3. Puxa as configurações do projeto da Vercel (usando seus secrets)
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      # 4. Faz o "build" do seu projeto (ex: compilar o código, otimizar)
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # 5. Finalmente, faz o deploy do projeto construído para a Vercel
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}